# Temel imajı belirle
FROM alpine:latest

# Build argümanını tanımla ve varsayılan bir değer ataması yap
ARG MESSAGE="Merhaba, Dünya!"

# Build argümanının değerini kullanarak bir dosyaya yazdır
RUN echo "$MESSAGE" > /tmp/mesaj.txt
